name: assistant
description: Assistant for the app.
publish_to: none
version: 2.1.13

environment:
  sdk: ^3.6.0

dependencies:
  bot_toast: ^4.1.3
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  json_annotation: ^4.9.0
  package_info_plus: ^8.2.0
  sentry_flutter: ^8.14.1
  shared_preferences: ^2.3.4
  ttpos_api: ^0.0.1
  ttpos_i18n: ^0.0.1
  ttpos_logger: ^0.0.1
  ttpos_model: ^0.0.1
  ttpos_shared: ^0.0.1
  ttpos_ui: ^0.0.1
  uuid: ^4.4.2
  wakelock_plus: ^1.3.2
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  import_sorter: ^4.6.0
  json_serializable: ^6.9.0
  rename_app: ^1.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

import_sorter:
  emojis: false
  comments: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/images/logo_square.png"
  adaptive_icon_background: "#FFBE00"
  adaptive_icon_foreground: "assets/images/logo_square.png"
  adaptive_icon_foreground_inset: 16
  min_sdk_android: 16 # android min sdk min:16, default 21
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/logo_square.png"
  background_color_ios: "#FFBE00"
  web:
    generate: true
    image_path: "assets/images/logo_web.png"
    background_color: "#FAFAFA"
    theme_color: "#FFBE00"
  windows:
    generate: true
    image_path: "assets/images/logo_square.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_macos.png"
