version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: ttpos-nginx
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    restart: always

  menu:
    image: hub.hitosea.com/ttpos-web/ttpos-web-menu:${IMAGE_TAG}
    container_name: ttpos-menu    
    restart: always

  mobile:
    image: hub.hitosea.com/ttpos-web/ttpos-web-mobile:${IMAGE_TAG}
    container_name: ttpos-mobile
    restart: always
