name: pos
description: Point of Sale for the app.
publish_to: none
version: 2.1.13

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.1.2
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.2
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_tts: 4.2.3
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  json_annotation: ^4.9.0
  omni_datetime_picker: ^2.1.1
  package_info_plus: ^8.2.0
  pagination_flutter: ^0.0.8
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  sentry_flutter: ^8.14.1
  shared_preferences: ^2.3.4
  ttpos_api: ^0.0.1
  ttpos_flutter_subscreen_plugin: ^0.0.1
  ttpos_i18n: ^0.0.1
  ttpos_logger: ^0.0.1
  ttpos_model: ^0.0.1
  ttpos_shared: ^0.0.1
  ttpos_ui: ^0.0.1
  usb_serial: ^0.5.2
  uuid: ^4.4.2
  video_player: ^2.9.3
  wakelock_plus: ^1.3.2
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  import_sorter: ^4.6.0
  intl_translation: ^0.20.0
  json_serializable: ^6.9.0
  rename_app: ^1.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/libhttpserver.so
    - assets/images/
    - assets/media/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

import_sorter:
  emojis: false
  comments: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/images/logo_square.png"
  adaptive_icon_background: "#FFBE00"
  adaptive_icon_foreground: "assets/images/logo_square.png"
  adaptive_icon_foreground_inset: 16
  min_sdk_android: 16 # android min sdk min:16, default 21
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/logo_square.png"
  background_color_ios: "#FFBE00"
  web:
    generate: true
    image_path: "assets/images/logo_web.png"
    background_color: "#FAFAFA"
    theme_color: "#FFBE00"
  windows:
    generate: true
    image_path: "assets/images/logo_square.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_macos.png"
