name: server
description: Server for the app.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  orm: ^5.2.1
  orm_flutter: ^0.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shelf: ^1.4.2
  shelf_multipart: ^2.0.0
  ttpos_shared: ^0.0.1
  cron: ^0.6.1
  shelf_router: ^1.1.4
  pdfx: ^2.8.0
  luthor: ^0.5.2+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  assets:
    # fonts
    - assets/fonts/
    - assets/fonts/noto_sans/
    - assets/fonts/noto_sans/en/
    - assets/fonts/noto_sans/jp/
    - assets/fonts/noto_sans/kr/
    - assets/fonts/noto_sans/my/
    - assets/fonts/noto_sans/th/
    - assets/fonts/noto_sans/tr/
    - assets/fonts/noto_sans/zh/
    - assets/fonts/noto_sans/zhTW/
    # prisma
    - prisma/
    - prisma/migrations/
    - prisma/migrations/20241228160027_init/

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

import_sorter:
  emojis: false
  comments: true
  ignored_files:
    - \/lib\/prisma\/*
