name: ttpos_ui
description: The UI package for the app.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  animated_text_kit: ^4.2.2
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  crypto: ^3.0.6
  decimal: ^3.0.2
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  dropdown_search: ^6.0.2
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.7.0
  flutter_svg: ^2.0.17
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  timezone: ^0.10.0
  ttpos_api: ^0.0.1
  ttpos_flutter_subscreen_plugin: ^0.0.1
  ttpos_i18n: ^0.0.1
  ttpos_logger: ^0.0.1
  ttpos_model: ^0.0.1
  ttpos_shared: ^0.0.1
  url_launcher: ^6.2.5
  usb_serial: ^0.5.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login_bg.png
    - assets/images/empty.svg
    - assets/images/search_keyword_empty.png
    - assets/images/tt_empty.png
    # - assets/fonts/google_fonts/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

import_sorter:
  emojis: false
  comments: true
